name: perception_temporal_action_loc

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Build tools - matching Ubuntu 22.04 versions
  - gcc=11.4.0
  - gxx=11.4.0
  - ninja
  - cmake
  - make
  - libgomp
  
  # Core Python & PyTorch - matching Colab versions
  - python=3.11
  - pytorch=2.5
  - torchvision=0.20
  - torchaudio=2.5
  - cuda-toolkit=12.2.2
  - tensorboard=2.17
  
  # Scientific stack - matching Colab versions
  - numpy=1.26.4
  - scipy=1.13.1
  - pandas=2.2.2
  - pyyaml
  - h5py=3.12.1
  - joblib=1.4.2
  - pip

  - pip:
      - gdown