name: llm-merging
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.13
  - python=3.10.14
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - torchtriton=2.2.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==2.1.0
    - accelerate==1.0.1
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - altair==5.3.0
    - annotated-types==0.6.0
    - anyio==4.3.0
    - appdirs==1.4.4
    - astor==0.8.1
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.2.0
    - base58==2.1.1
    - bitsandbytes==0.44.1
    - black==21.12b0
    - bleach==6.1.0
    - blinker==1.7.0
    - brotli==1.1.0
    - cachetools==5.3.3
    - certifi==2024.2.2
    - chardet==5.2.0
    - charset-normalizer==3.1.0
    - click==8.1.7
    - colorama==0.4.6
    - dataproperty==1.1.0
    - datasets==2.18.0
    - decorator==5.1.1
    - dill==0.3.8
    - distro==1.9.0
    - evaluate==0.4.1
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fire==0.6.0
    - flake8==7.0.0
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.27.0
    - idna==3.4
    - immutables==0.20
    - inflate64==1.0.0
    - iniconfig==2.0.0
    - ipdb==0.13.13
    - ipython==8.23.0
    - isort==5.8.0
    - jax==0.4.6
    - jaxlib==0.4.6+cuda11.cudnn86
    - jedi==0.19.1
    - jinja2==3.1.3
    - jiter==0.7.1
    - joblib==1.4.0
    - jsonlines==4.0.0
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - kaggle==1.6.17
    - llm-merging==1.0
    - lm-eval==0.4.7
    - lxml==5.3.0
    - mando==0.7.1
    - matplotlib-inline==0.1.6
    - mbstrdecoder==1.1.3
    - mccabe==0.7.0
    - mergekit==0.0.5.2
    - more-itertools==10.5.0
    - multidict==6.0.5
    - multipledispatch==1.0.0
    - multiprocess==0.70.16
    - multivolumefile==0.2.3
    - mypy-extensions==1.0.0
    - networkx==3.1
    - nltk==3.8.1
    - numexpr==2.10.2
    - openai==1.57.0
    - opt-einsum==3.3.0
    - packaging==24.0
    - pandas==2.2.1
    - parso==0.8.4
    - pathspec==0.12.1
    - pathvalidate==3.2.1
    - peft==0.10.0
    - pexpect==4.9.0
    - pillow==10.2.0
    - pip==24.0
    - platformdirs==4.3.6
    - plotly==5.20.0
    - pluggy==1.4.0
    - portalocker==3.1.1
    - prompt-toolkit==3.0.43
    - promptsource==0.2.3
    - protobuf==5.26.1
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py7zr==0.21.0
    - pyarrow==15.0.2
    - pyarrow-hotfix==0.6
    - pybcj==1.0.2
    - pybind11==2.13.6
    - pycodestyle==2.11.1
    - pycryptodomex==3.20.0
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pydeck==0.8.1b0
    - pyflakes==3.2.0
    - pyg-lib==0.4.0+pt20cu117
    - pygments==2.17.2
    - pyppmd==1.1.0
    - pytablewriter==1.2.0
    - pytest==8.1.1
    - python-dateutil==2.9.0.post0
    - python-slugify==8.0.4
    - pytz==2024.1
    - pyzstd==0.15.10
    - referencing==0.34.0
    - regex==2023.12.25
    - requests==2.31.0
    - responses==0.18.0
    - rouge-score==0.1.2
    - rpds-py==0.18.0
    - sacrebleu==2.4.3
    - safetensors==0.4.5
    - scikit-learn==1.4.2
    - scipy==1.13.0
    - sentencepiece==0.2.0
    - setuptools==68.2.2
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - sqlitedict==2.1.0
    - stack-data==0.6.3
    - streamlit==0.82.0
    - sympy==1.12
    - tabledata==1.3.4
    - tabulate==0.9.0
    - tcolorpy==0.1.7
    - tempdir==0.7.1
    - tenacity==8.2.3
    - termcolor==2.4.0
    - text-unidecode==1.3
    - texttable==1.7.0
    - threadpoolctl==3.4.0
    - tiktoken==0.8.0
    - tinybenchmarks==1.0.0
    - tokenizers==0.21.0
    - toml==0.10.2
    - tomli==1.2.3
    - toolz==0.12.1
    - torch-cluster==1.6.3+pt20cu117
    - torch-scatter==2.1.2+pt20cu117
    - torch-sparse==0.6.18+pt20cu117
    - torchaudio==2.2.2
    - torchvision==0.17.2
    - tornado==6.4
    - tqdm==4.66.5
    - tqdm-multiprocess==0.0.11
    - traitlets==5.14.2
    - transformers==4.47.1
    - tree-sitter==0.21.3
    - tree-sitter-languages==1.10.2
    - typepy==1.3.4
    - typing-extensions==4.12.2
    - typing-inspect==0.8.0
    - tzdata==2024.1
    - tzlocal==5.2
    - urllib3==2.1.0
    - validators==0.28.0
    - watchdog==4.0.0
    - wcwidth==0.2.13
    - webencodings==0.5.1
    - wget==3.2
    - wheel==0.41.2
    - word2number==1.1
    - xxhash==3.4.1
    - yarl==1.9.4
    - zstandard==0.23.0
